In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('seaborn-talk')

# clean data as in previous example

meses = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
         'Julio', 'Agosto', 'Setiembre', 'Octubre', 'Noviembre', 'Diciembre']
mesescorto = [x[:3] for x in meses]
meses2 = {mes: i for i, mes in enumerate(meses, start=1)}

# Leer y limpiar datos
FILENAME = "datos/Datos-ARESEP-Pasajeros-por-aeropuerto.csv"
SJO = pd.read_csv(FILENAME)
SJO.query('Aeropuerto =="Aeropuerto Internacional Juan Santamaría"', inplace=True)
SJO.replace(meses2, None,inplace=True)
SJO.sort_values(['Año','Mes'], inplace=True)
SJO.index = pd.period_range(start=f"{SJO['Año'].iloc[0]}-{SJO['Mes'].iloc[0]}", periods=SJO.shape[0], freq='M')
SJO.drop(['Aeropuerto', 'Mes', 'Año', 'Cantidad En Tránsito', 'Cantidad Exentos','Total Pasajeros'], axis=1,inplace=True)
SJO.rename(columns={'Cantidad Nacionales':'nacionales', 'Cantidad Extrajeros':'extranjeros'}, inplace=True)

sjodatos = SJO/1000
sjodatos.index = pd.MultiIndex.from_arrays([sjodatos.index.year, sjodatos.index.month])
sjodatoscuadro = sjodatos.unstack()

In [2]:
sjodatoscuadro['extranjeros'].round(1)

,1,2,3,4,5,6,7,8,9,10,11,12
2011,116.3,105.4,128.9,103.1,82.7,88.0,103.3,102.9,64.6,62.6,77.5,90.3
2012,115.8,108.1,130.9,106.0,82.2,89.1,105.9,105.7,67.8,60.4,79.3,92.4
2013,122.9,109.6,133.0,108.5,85.3,95.0,110.3,112.8,70.0,67.3,83.5,107.7
2014,132.3,120.9,146.3,111.9,93.1,96.4,111.4,116.8,71.7,67.3,85.3,104.9
2015,137.2,122.7,143.8,122.8,96.5,105.1,121.5,129.9,79.6,76.4,100.5,122.6
2016,149.2,141.8,161.3,132.0,108.1,113.3,134.6,138.7,84.5,83.2,102.4,124.2
2017,153.6,145.1,179.0,148.7,119.4,126.8,141.0,142.8,97.9,90.2,117.1,135.0
2018,165.7,161.1,189.4,161.3,127.4,134.1,148.9,156.0,100.3,93.9,120.4,140.7
2019,185.3,170.4,206.7,157.0,128.2,137.0,151.4,156.4,101.2,102.0,122.1,153.3